import { CreateProductDto } from '../catalog/dto/create-product.dto';

export const SEED_PRODUCTS: CreateProductDto[] = [
  {
    sku: 'JK-RAIN-01',
    name: '라이트 레인 자켓',
    description: '비 오는 날 입기 좋은 가벼운 방수 자켓. 통근과 주말 여행에 맞춘 슬림 핏.',
    category: 'outer',
    price: 89000,
    tags: ['자켓', '비', '가벼운', '방수'],
  },
  {
    sku: 'UM-COMPACT-02',
    name: '컴팩트 우산',
    description: '가방에 들어가는 가벼운 우산. 갑작스러운 비에 대비하는 데일리 아이템.',
    category: 'accessory',
    price: 24000,
    tags: ['우산', '비', '가벼운'],
  },
  {
    sku: 'CD-KNIT-03',
    name: '데일리 니트 가디건',
    description: '서늘한 저녁에 걸치기 좋은 얇은 가디건. 사무실과 주말에 두루 입는다.',
    category: 'outer',
    price: 54000,
    tags: ['가디건', '니트', '데일리'],
  },
  {
    sku: 'SN-RUN-04',
    name: '런닝 라이트 스니커즈',
    description: '가벼운 쿠셔닝의 러닝화. 비 온 뒤 젖은 길에서도 접지력이 좋다.',
    category: 'shoes',
    price: 79000,
    tags: ['스니커즈', '러닝', '가벼운'],
  },
  {
    sku: 'LP-WORK-05',
    name: '14인치 업무용 노트북',
    description: '문서와 영상 회의를 위한 14인치 노트북. 가벼운 무게와 긴 배터리.',
    category: 'electronics',
    price: 1290000,
    tags: ['노트북', '업무', '가벼운'],
  },
  {
    sku: 'KB-MECH-06',
    name: '저소음 기계식 키보드',
    description: '사무실에서 쓰기 좋은 저소음 기계식 키보드. 타건감과 정숙성을 같이 맞췄다.',
    category: 'electronics',
    price: 119000,
    tags: ['키보드', '기계식', '사무'],
  },
  {
    sku: 'MS-GAME-07',
    name: '무선 게이밍 마우스',
    description: '지연이 낮은 무선 게이밍 마우스. 장시간 사용에도 가벼운 본체.',
    category: 'electronics',
    price: 69000,
    tags: ['마우스', '게이밍', '무선'],
  },
  {
    sku: 'HP-NOISE-08',
    name: '노이즈캔슬링 헤드폰',
    description: '출퇴근 소음을 줄이는 헤드폰. 통화와 음악에 모두 맞춘 튜닝.',
    category: 'electronics',
    price: 189000,
    tags: ['헤드폰', '노이즈캔슬링', '출퇴근'],
  },
  {
    sku: 'CF-DRIP-09',
    name: '홈카페 드립 세트',
    description: '집에서 핸드드립을 시작하는 서버와 드리퍼 세트. 주말 아침용.',
    category: 'living',
    price: 42000,
    tags: ['커피', '드립', '홈카페'],
  },
  {
    sku: 'CP-CHAIR-10',
    name: '캠핑 경량 체어',
    description: '접어서 들고 가는 가벼운 캠핑 체어. 피크닉과 단기 캠핑용.',
    category: 'living',
    price: 36000,
    tags: ['캠핑', '체어', '가벼운'],
  },
];
